### DISCUSSION TITLE
How to widen the width of the content and move the content to the left

### DISCUSSION THREAD

**Discussion by kurt-krueckeberg** [piccolo-orm/piccolo_theme#42] [Q&A]
First, thanks for the Piccolo theme for Sphinx!  The dark mode support is great to have in a theme.

What is the best way to widen the content width? And is it possible to move the content to the left, so its closer to the navigation?

**Comment by dantownsend** [comment]
Thanks! The dark mode definitely makes things easier on the eyes.

The best way to align the content to the left currently is to customise the CSS:

```css
div.documentwrapper {
    margin: 0;
}
```

Similarly, to make the content wider:

```css
div.documentwrapper {
    max-width: 60rem;
}
```

You should be able to add a custom CSS file using [this](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files).

I might add this as a proper feature, so it can be configured in `html_theme_options`.

**Reply by kurt-krueckeberg** [reply]
Thanks for the prompt reply. Having these options in `html_theme_options` would be fantastic.

**Reply by kurt-krueckeberg** [reply]
Actually, I needed this in my `_static/custom.css`:

```css
div.document div.documentwrapper {
    margin: 0;
    max-width: 60rem;
}
```
