### DISCUSSION TITLE
is possible to setup for github pages?

### DISCUSSION THREAD

**Discussion by israpps** [piccolo-orm/piccolo_theme#44] [Q&A]
as title says.

Can this be used via gh pages?

**Comment by kurt-krueckeberg** [comment]
Did you look at the Hugo documentation to [Host on Github](https://gohugo.io/hosting-and-deployment/hosting-on-github/)?

**Comment by dantownsend** [comment]
@israpps Yeah, as @kurt-krueckeberg says the deployment method for GitHub Actions is pretty similar for all static site generators.

With Sphinx you just need to `cd` into your documentation folder, then run `make html`, and upload the results as a build artefact.

You can check out this pre-built GitHub action:

https://github.com/marketplace/actions/sphinx-build

Or you can just write your own GitHub action from scratch.

I use GitLab to publish my docs, but the principals are the same:

```yaml
pages:
    stage: build
    image: python:3.10-slim-bullseye
    script:
        - pip install -r doc-requirements.txt
        - cd docs && make html
        - cp -r _build/html/* /public
    artifacts:
        paths:
            - /public
```

You can also use [Read The Docs](https://readthedocs.org/) to publish your docs if you prefer.
